# Generated by Django 5.1.4 on 2024-12-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'ПРОФИЛЬ', 'verbose_name_plural': 'ПРОФИЛИ'},
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='EMAIL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, verbose_name='FACEBOOK'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, verbose_name='INSTAGRAM'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, verbose_name='LINKEDIN'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='ТЕЛЕФОН'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='ДОЛЖНОСТЬ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='TELEGRAM'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, verbose_name='TWITTER'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, verbose_name='САЙТ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, verbose_name='WHATSAPP'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(help_text='Рекомендуемый размер 100x100', upload_to='avatars/', verbose_name='ФОТО'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер 530x200', null=True, upload_to='backgrounds/', verbose_name='ФОН'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='ДЕНЬ РОЖДЕНИЯ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='КОМПАНИЯ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_birthday',
            field=models.BooleanField(default=False, verbose_name='ПОКАЗЫВАТЬ ДЕНЬ РОЖДЕНИЯ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hash',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(blank=True, verbose_name='МОЯ ЭЛЕКТРОННАЯ ВИЗИТКА'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_trial',
            field=models.BooleanField(default=True, verbose_name='ПРОБНЫЙ ПЕРИОД'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ИМЯ'),
        ),
    ]
