# Generated by Django 5.1.4 on 2024-12-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_options_profile_email_profile_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер 100x100', null=True, upload_to='avatars/', verbose_name='ФОТО'),
        ),
    ]
