# Generated by Django 5.2.5 on 2025-09-22 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=512, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=512, verbose_name='FACEBOOK'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hash',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=512, verbose_name='INSTAGRAM'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=512, verbose_name='LINKEDIN'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='ТЕЛЕФОН'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=512, verbose_name='TELEGRAM'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=512, verbose_name='TWITTER'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, max_length=1024, verbose_name='САЙТ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=512, verbose_name='WHATSAPP'),
        ),
        migrations.CreateModel(
            name='NfcCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128, unique=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('tap_count', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_cards', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'NFC карта',
                'verbose_name_plural': 'NFC карты',
            },
        ),
        migrations.CreateModel(
            name='ProfileWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('button', 'Кнопка'), ('link', 'Ссылка'), ('text', 'Текст'), ('social', 'Социальная сеть'), ('contact', 'Контакт')], default='button', max_length=20)),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Содержимое/URL')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (Font Awesome)')),
                ('color', models.CharField(default='#007AFF', max_length=7, verbose_name='Цвет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Виджет профиля',
                'verbose_name_plural': 'Виджеты профиля',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
