# Generated by Django 5.2.5 on 2025-10-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_email_alter_profile_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Цвет общего фона страницы (за кнопками)', max_length=7, verbose_name='ЦВЕТ ФОНА (СТРАНИЦЫ)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme_line_color',
            field=models.CharField(default='#E6E6E6', help_text='Цвет линий разделителей и границ', max_length=7, verbose_name='ЦВЕТ ЛИНИЙ/ГРАНИЦ'),
        ),
    ]
