# Generated by Django 5.2.5 on 2025-10-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_theme_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme_page_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Фон за шапкой и контентом всей страницы', max_length=7, verbose_name='ВНЕШНИЙ ФОН СТРАНИЦЫ'),
        ),
    ]
